# Day 4

In [2]:
# Numpy(numerical python)is a library for efficient numerical computation in python.

In [6]:
#Day 4: Python Basics + NumPy Introduction
# 1. Python Keywords & Data Types

In [8]:
# List all keywords in python
import keyword
print("python keywords:",keyword.kwlist)

python keywords: ['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [10]:
# Basic data types
a = 10 #int
b = 3.14 #float
c = 'movie' # string
d = True # bool
print(type(a),type(b),type(c),type(d))

<class 'int'> <class 'float'> <class 'str'> <class 'bool'>


In [ ]:

import numpy as np

In [66]:
# 1. Load and Clean the Dataset (Using Pandas)

import pandas as pd

# Load the dataset
df = pd.read_csv('movies_metadata.csv', low_memory=False)

# Keep only title and vote_average columns
df = df[['title', 'vote_average']]

# Remove missing and invalid values
df = df.dropna(subset=['vote_average']) # average rating of a movie
df['vote_average'] = pd.to_numeric(df['vote_average'], errors='coerce')
df = df.dropna(subset=['vote_average'])  # Remove non-numeric ratings  # dropna remove rows or
# columns with missing or null values from a dataframe
# Show first 5 cleaned rows
print(df.head())

                         title  vote_average
0                    Toy Story           7.7
1                      Jumanji           6.9
2             Grumpier Old Men           6.5
3            Waiting to Exhale           6.1
4  Father of the Bride Part II           5.7


In [68]:
#1: Simulate Movie Ratings-stimulate movie means artificially 
#influencing online movie scores through fake or biased reviews.

import numpy as np

# Simulated ratings array
ratings = np.array([4.8, 3.2, 2.9, 4.5, 1.5, 3.9, 2.1, 4.6, 3.6, 2.8])

print("All Ratings:", ratings)

All Ratings: [4.8 3.2 2.9 4.5 1.5 3.9 2.1 4.6 3.6 2.8]


In [38]:
#2: Python Data Types
movie_name = "Inception"
rating     =  ratings # numpy.ndarray is used to store and work with lage,multi-dimensional
#arrays.
release_year = 2010
is_available = True
print(type(movie_name),type(rating),type(release_year),type(is_available))

<class 'str'> <class 'numpy.ndarray'> <class 'int'> <class 'bool'>


In [74]:
#3: Use if-else for a Sample Rating
import numpy as np
rating = 4.2   
if rating > 4.5:
    print("Excellent movie")
elif rating > 3.5:
    print("Good movie")
else:
    print("Average movie")
    


Good movie


In [76]:
#4. NumPy Basics on Ratings
import numpy as np
# Convert vote_average column to NumPy array
ratings = df['vote_average'].to_numpy()

# Print basic statistics
print("Mean Rating:", np.mean(ratings)) #avg value of a dataset
print("Max Rating:", np.max(ratings))
print("Min Rating:", np.min(ratings))

Mean Rating: 5.618207215134184
Max Rating: 10.0
Min Rating: 0.0


In [78]:
 #5. NumPy Filtering: High Ratings
# Filter ratings > 7

high_ratings = ratings[ratings > 7]

print("High Ratings (first 5):", high_ratings[:5])
print("Total High Rated Movies:", len(high_ratings))

High Ratings (first 5): [7.7 7.7 7.1 7.1 7.8]
Total High Rated Movies: 7714


# Day 5: NumPy Arrays + Python Basics + Mini Project

In [2]:
# #NumPy Arrays
# creating NumPy Arrays
# Numpy Array Indexing and Slicing
# Reshaping and Resizing Arrays
# Stacking and Splitting Arrays
# Broadcasting in NumPy

# #Mathematical Operations in NumPy
# Basic Arithmetic Operations
# Aggregation Functions (sum, mean, max, min)
# Universal Functions in Numpy
# Mathematical Functions in Numpy


In [16]:
#1 NumPy Array Basics
#import numpy as np
arr1 = np.array([10,20,30])
arr2 = np. array([[1,2],[3,4]])
print(arr1 ,arr2)

[10 20 30] [[1 2]
 [3 4]]


In [18]:
#2.Indexing and Slicing- are used to access and extract specific elements or parts of a sequences like strings,lists, or tuples.
# or   indexing gets a single item; slicing gets a range of items from a sequence.
#import numpy as np
print(arr1[0])  # 10
print(arr2[1:3])   # [20 30]
ratings = [5, 4, 3, 2, 1, 0]
print(ratings[:5])  # first 5 movie ratings.


10
[[3 4]]
[5, 4, 3, 2, 1]


In [93]:
#3: Reshaping and Resizing Arrays

arr = np.arange(6)   # [0,1,2,3,4,5]
reshaped = np.reshape(arr,(2,3))  # 2*3 matrix  [reshape fun is used to change the shape and size of an array]
resized = np.resize(arr, (3,4))   #repeats values if needed  [resize fun is used to changes the shape and size of an array]
print("original array:",arr)
print("reshaped (2*3):\n",reshaped)
print("resized (3*4):\n",resized)

original array: [0 1 2 3 4 5]
reshaped (2*3):
 [[0 1 2]
 [3 4 5]]
resized (3*4):
 [[0 1 2 3]
 [4 5 0 1]
 [2 3 4 5]]


In [95]:
#4: Stacking and Splitting Arrays
a = np.array([1,2,3])
b = np.array([4,5,6])
vstacked = np.vstack((a,b)) # vertical stack
hstacked = np.hstack((a,b)) #horizontal stack
split    = np.split(hstacked ,2)  # split into two arrays
print("vertical stack:", vstacked)
print("horizontal stack:", hstacked)
print("split into two parts:", split)


vertical stack: [[1 2 3]
 [4 5 6]]
horizontal stack: [1 2 3 4 5 6]
split into two parts: [array([1, 2, 3]), array([4, 5, 6])]


In [97]:
 #5: Broadcasting [ broadcasting in numpy aligns arrays with different shapes for element-wise operations.]
adjusted_ratings = ratings[:5] + 1 # add 1 to first 5 ratings
print("original ratings:", ratings)
print("adjusted first 5 ratings (+1):",adjusted_ratings)

original ratings: [7.7 6.9 6.5 ... 3.8 0.  0. ]
adjusted first 5 ratings (+1): [8.7 7.9 7.5 7.1 6.7]


In [99]:
# 6: Python Conditional Statements + Loop with NumPy
# Conditional & Data Types
vote = 1500
rating = 8.3
if vote > 1000 and rating > 8:
    print("Hit Movie")

Hit Movie


In [101]:
 #For Loop with Ratings
for i in range(len(ratings)):
    if ratings[i] > 8:
        print(df.iloc[i]['title'],":",ratings[i])
        if i == 4: break # show only first 5 movies.

Se7en : 8.1
The Usual Suspects : 8.1
Taxi Driver : 8.1
Reckless : 10.0
Star Wars : 8.1
Leon: The Professional : 8.2
Pulp Fiction : 8.3
The Shawshank Redemption : 8.5
Forrest Gump : 8.2
Girl in the Cadillac : 10.0
Schindler's List : 8.3
The Silence of the Lambs : 8.1
The World of Apu : 8.2
The Haunted World of Edward D. Wood, Jr. : 10.0
Carmen Miranda: Bananas Is My Business : 10.0
The Godfather : 8.5
Rear Window : 8.2
The Apartment : 8.1
Sunset Boulevard : 8.2
The Scarlet Letter : 8.3
Reservoir Dogs : 8.1
Cinema Paradiso : 8.2
Paths of Glory : 8.2
Paris is Burning : 8.2
One Flew Over the Cuckoo's Nest : 8.3
The Empire Strikes Back : 8.2
The Good, the Bad and the Ugly : 8.1
12 Angry Men : 8.2
Once Upon a Time in the West : 8.1
GoodFellas : 8.2
Psycho : 8.3
The Godfather: Part II : 8.3
Once Upon a Time in America : 8.3
Dead Poets Society : 8.1
The Shining : 8.1
The Great Dictator : 8.1
Vampire in Venice : 8.5
Love Jones : 8.1
Fast, Cheap & Out of Control : 8.3
Other Voices Other Rooms : 

In [107]:
#1. Basic Arithmetic Operations

import numpy as np

x = np.array([10, 20, 30])
y = np.array([1, 2, 3])

print("Addition:", x + y)        # [11 22 33]
print("Subtraction:", x - y)     # [9 18 27]
print("Multiplication:", x * y)  # [10 40 90]
print("Division:", x / y)        # [10. 10. 10.]

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]


In [113]:
# 2. Aggregation Functions
# Used for summarizing [like sum, mean, and median on arrays]
ratings = np.array([6.5, 7.2, 8.0, 5.9, 6.8, 7.5])
votes = np.array([120, 250, 310, 90, 150, 200])

print("Total Votes:", np.sum(votes))
print("Average Rating:", np.mean(ratings))
print("Highest Rating:", np.max(ratings))
print("Lowest Rating:", np.min(ratings))

Total Votes: 1120
Average Rating: 6.983333333333333
Highest Rating: 8.0
Lowest Rating: 5.9


In [115]:
 #3. Universal Functions (ufuncs)
# Element-wise operations with optimization

print("Square Root of Votes:", np.sqrt(votes[:5]))
print("Log of Votes:", np.log1p(votes[:5]))      # log(1 + x)
print("Exponential of Ratings:", np.exp(ratings[:5]))

Square Root of Votes: [10.95445115 15.8113883  17.60681686  9.48683298 12.24744871]
Log of Votes: [4.79579055 5.52545294 5.73979291 4.51085951 5.01727984]
Exponential of Ratings: [ 665.14163304 1339.43076439 2980.95798704  365.03746787  897.84729165]


In [117]:
# 4. Mathematical Functions

angles = np.array([0, np.pi/2, np.pi])
print("Sine:", np.sin(angles))
print("Cosine:", np.cos(angles))
print("Tangent:", np.tan(angles))

Sine: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Tangent: [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [119]:
# Apply on ratings:

print("Rounded Ratings:", np.round(ratings[:5]))   # Round-off values

Rounded Ratings: [6. 7. 8. 6. 7.]


# Mini Project (Day 5): Filter Movies with Rating > 8 using Loop

 #: Filter Movies with Rating > 8 using Loop
print(" movies by rating > 8:\n")
for i in range(len(ratings)):
    if ratings[i] > 8:
        print(f"{df.iloc[i]['title']} - rating: {ratings[i]}")
        if i == 9: break #only top 10

# Day 6

In [124]:
# Linear Algebra with NumPy


# Matrix Multiplication and Manipulation
# Matrix & vector products in Numpy
# Determinants and Inverse of a Matrix
# Inner and Outer Functions
# Dot and Vdot Functions
# Eigenvalues and Eigenvectors


# Random Number Generation and Statistics
# Generating Random Numbers
# Normal Distribution
# Binomial Distribution
# Poisson Distribution
# Uniform Distribution
# Exponential Distribution
# Chi-square Distribution
# Statistical Functions (mean, median, variance, standard deviation)


# Advanced NumPy Operations
# Vectorized Operations for Performance Optimization
# Broadcasting in Numpy
# Sparse Matrices in Numpy
# Working with Images in Numpy

In [126]:
 #1. Linear Algebra in NumPy
# Matrix Multiplication & Manipulation 
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print("matrix multiplication:\n", np.dot(A,B))  # or A @ B

matrix multiplication:
 [[19 22]
 [43 50]]


In [128]:
# Matrix & Vector Products
v = np.array([1,2])
w = np.array([3,4])    # 1*3 + 2*4 = 11
print("dot product:",np.dot(v,w))


dot product: 11


In [130]:
# Determinants and Inverse
M = np.array([[2,1],[5,3]])
print("determinants:",np.linalg.det(M))
print("inverse:",np.linalg.inv(M))




determinants: 1.0000000000000002
inverse: [[ 3. -1.]
 [-5.  2.]]


In [132]:
 # Inner and Outer Product
print("inner:",np.inner(v,w))  # inner product:dot product of two vectors(scalar result)
print("outerr:",np.outer(v,w))  #outer product:product of two vectors(matrix result)


inner: 11
outerr: [[3 4]
 [6 8]]


In [136]:
 # Dot and Vdot Functions
print("dot:",np.dot(v,w))  # np.dot():Dot product (matrix multiplication).
print("vdot:",np.vdot(v,w)) # np.vdot(): Dot product of vectors(with complex conjugate).

dot: 11
vdot: 11


In [138]:
# Eigenvalues and Eigenvectors
x = np.array([[2,-1],[-1,2]])  
eigenvalues,eigenvectors = np.linalg.eig(x) # eigenvalues:scalar values representing how much change occurs in a linear transformation.
print("eigenvalues:",eigenvalues)
print("eigenvectors:",eigenvectors) #eigenvectors:direction vectors that do not change direction under a linear transformation.

eigenvalues: [3. 1.]
eigenvectors: [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


In [140]:
# 2. Random Number Generation & Distributions
# Set seed for reproducibility
np.random.seed(42)
print("normal:",np.random.normal(0,1,5))  # mean=0, std=1
print("binomial:",np.random.binomial(10,0.5,5))  # 10 trials, p=0.5
print("poisson:",np.random.poisson(3,5))  # lambda=3
print("uniform:",np.random.uniform(1,10,5))  # low=1, high=10
print("exponential:",np.random.exponential(1,5))  # scale=1
print("chi square:",np.random.chisquare(2,5)) # df=2

normal: [ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]
binomial: [3 7 5 6 2]
poisson: [3 2 3 2 3]
uniform: [1.41805371 6.46790367 2.53471711 1.58546434 9.53996984]
exponential: [3.37063034 1.65233157 0.36328786 0.10277732 1.15275076]
chi square: [1.16018169 0.26030447 1.36709446 0.06998744 4.80084577]


In [145]:
# 3. Statistical Functions (on movie data)
print("ratings - Mean:",np.mean(ratings))
print("ratings - Median:",np.median(ratings))
print("ratings - variance:",np.var(ratings))
print("ratings - std Dev:",np.std(ratings))


ratings - Mean: 6.983333333333333
ratings - Median: 7.0
ratings - variance: 0.4647222222222221
ratings - std Dev: 0.6817053778739186


In [161]:
# 4. Advanced NumPy Operations
# Vectorized Weighted Score (for movie ranking)
# Normalize vote_count

# Load dataset
df = pd.read_csv("movies_metadata.csv", low_memory=False)

# Select and clean data
df = df[['title', 'vote_average', 'vote_count']].dropna()
df['vote_count'] = pd.to_numeric(df['vote_count'], errors='coerce')
df = df.dropna()

# Convert to NumPy arrays (these will match the cleaned df)
ratings = df['vote_average'].to_numpy()
votes = df['vote_count'].to_numpy()

# 1. Normalize vote counts
norm_votes = (votes - votes.min()) / (votes.max() - votes.min())

# 2. Vectorized weighted score = rating × normalized vote count
df['score'] = ratings * norm_votes

# 3. Top 5 movies by score
top5 = df.sort_values(by='score', ascending=False)[['title', 'vote_average', 'vote_count', 'score']].head()

# 4. Print results
print(top5)


                 title  vote_average  vote_count     score
15480        Inception           8.1     14075.0  8.100000
12481  The Dark Knight           8.3     12269.0  7.235005
22879     Interstellar           8.1     11187.0  6.437989
17818     The Avengers           7.4     12000.0  6.309059
14551           Avatar           7.2     12114.0  6.196860


In [163]:
# Sparse Matrix Example
from scipy.sparse import csr_matrix
dense = np.array([[0,0,3],[4,0,0]])
sparse = csr_matrix(dense)
print("sparse matrix:\n",sparse)

sparse matrix:
 <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (2, 3)>
  Coords	Values
  (0, 2)	3
  (1, 0)	4


In [175]:
# Working with Images (Optional Demo)

from PIL import Image
import numpy as np
import os

# Print working directory
print("Current directory:", os.getcwd())

# Try loading image
try:
    img = Image.open("sample.jpg")  # Replace with correct path
    img_arr = np.array(img)
    print("Image shape:", img_arr.shape)
except FileNotFoundError:
    print("Image file not found. Make sure 'sample.jpg' is in the folder:", os.getcwd())


Current directory: C:\Users\Acer Aspire 3
Image file not found. Make sure 'sample.jpg' is in the folder: C:\Users\Acer Aspire 3


# Day 6 Mini Project: Top Scored Movies using Weighted Ratings

In [182]:
# Already calculated weighted score in 'df["score"]'
top_movies = df.sort_values(by='score' , ascending=False)
print(" Top 5 movies by weighted score:\n", top_movies[['title', 'vote_average', 'vote_count', 'score']].head())

 Top 5 movies by weighted score:
                  title  vote_average  vote_count     score
15480        Inception           8.1     14075.0  8.100000
12481  The Dark Knight           8.3     12269.0  7.235005
22879     Interstellar           8.1     11187.0  6.437989
17818     The Avengers           7.4     12000.0  6.309059
14551           Avatar           7.2     12114.0  6.196860
